id: AF78B4EE0
base_file: f7417.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:33:44.502503
  last_modified_at: 2022-06-17 11:33:44.502506
