id: AF78B4EE0
base_file: f70A8.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:33:44.501341
  last_modified_at: 2022-06-17 11:33:44.501344
