id: AF78B4EE0
base_file: f5086.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:33:44.497141
  last_modified_at: 2022-06-17 11:33:44.497144
