id: AF78B4EE0
base_file: fBD86.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - it
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:33:44.511266
  last_modified_at: 2022-06-17 11:33:44.511269
