id: AF78B4EE0
base_file: f240F.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:33:44.493270
  last_modified_at: 2022-06-17 11:33:44.493274
